// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: '0.0.1',
  serverAdminUrl: 'http://localhost:8080/api/v1/admin',
  serverDefaultUrl: 'http://localhost:8080/api/v1/default',
  serverPublishUrl: 'http://localhost:8080/api/v1/publish',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR', 'vi-VN', 'zh-CN'],
  dbTable: ['users', 'roles', 'user_grants', 'role_grants'],
  languages: {
    'en-US': {
      text: 'English',
      abbr: '🇬🇧'
    },
    'zh-CN': {
      text: '简体中文',
      abbr: '🇨🇳'
    },
    'vi-VN': {
      text: 'VietNam',
      abbr: '🇭🇰'
    },
    'fr-FR': {
      text: 'French',
      abbr: '🇫🇷'
    }
  }
};
